# Generated by Django 2.2.24 on 2021-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixngo', '0003_auto_20210604_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_repairrequest',
            name='is_Fixed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='s_repairrequest',
            name='is_Fixed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
