# Generated by Django 2.2.24 on 2021-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixngo', '0004_auto_20210604_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_repairrequest',
            name='review',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='s_repairrequest',
            name='review',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
