# Generated by Django 2.2.24 on 2021-06-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fixers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixerprofile',
            name='is_Fixer',
        ),
    ]
